version: 2
jobs:
  test27:
    docker:
      - image: circleci/python:2.7-jessie
    steps:
      - checkout
      - run: python test.py
  test35:
    docker:
      - image: circleci/python:3.5-jessie
    steps:
      - checkout
      - run: python test.py

workflows:
  version: 2
  test:
    jobs:
      - test27
      - test35
